name: wasm
version: '2.0.0'
author: Ilya Rezvov
maintainer: rezvov.ilya@gmail.com
license: MIT
extra-source-files:
- README.md
- src/Language/Wasm/Parser.y
- src/Language/Wasm/Lexer.x
build-tools:
- alex >=3.1.3
- happy >=1.9.4
dependencies:
- base >=4.6 && <5.0

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - array
  - text
  - bytestring
  - mtl
  - transformers
  - containers
  - utf8-string
  - ieee754
  - cereal
  - vector
  - deepseq

executables:
  wasm:
    main: Main.hs
    source-dirs: exec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm
    - optparse-applicative
    - bytestring
    - base64-bytestring

tests:
  test:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - wasm
    - filepath
    - directory
    - text
    - bytestring
    - mtl
    - tasty
    - tasty-hunit
