name: wasm
version: '0.1.0'
author: Ilya Rezvov
maintainer: rezvov.ilya@gmail.com
license: MIT
extra-source-files:
- README.md
- src/Language/Wasm/Parser.y
- src/Language/Wasm/Lexer.x
build-tools:
- alex >=3.1.3
- happy >=1.9.4
dependencies:
- base >=4.6 && <5.0

library:
  source-dirs: src
  ghc-options:
  - -Wwarn
  - -fwarn-incomplete-patterns
  - -fwarn-unused-imports
  exposed-modules:
  - Language.Wasm.Lexer
  - Language.Wasm.Parser
  - Language.Wasm.Structure
  - Language.Wasm.Binary
  - Language.Wasm.Validate
  - Language.Wasm.Interpreter
  - Language.Wasm.Script
  - Language.Wasm.FloatUtils
  - Language.Wasm.Builder
  - Language.Wasm
  dependencies:
  - array
  - text
  - bytestring
  - mtl
  - transformers
  - containers
  - utf8-string
  - ieee754
  - cereal
  - vector
  - deepseq

tests:
  test:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - wasm
    - filepath
    - directory
    - text
    - bytestring
    - mtl
    - tasty
    - tasty-hunit
